name: clojars

on:
  push:
    tags: ['*']

jobs:
  clojars-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set TAG value from refs/tags/TAG
        run: echo ::set-env name=GIT_TAG::${GITHUB_REF#refs/tags/}

      - name: Install java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install clojure
        uses: DeLaGuardo/setup-clojure@3.4
        with:
          cli: '1.10.3.855'

      - name: Tests
        run: clojure -X:run-tests

      - name: Overwrite pom.xml
        run: |
          sed -i 's;<version/>;<version>${{ env.GIT_TAG }}</version>;' pom.xml
          sed -i 's;<tag/>;<tag>${{ github.sha }}</tag>;' pom.xml

      - name: Update pom.xml
        run: clojure -Spom

      - name: Debug pom.xml
        run: cat pom.xml

      - name: Build jar
        run : clojure -X:uberjar

      - name: Deploy to Clojars
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_TOKEN }}
        run: clojure -X:clojars-deploy

      - name: Slack notifications
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: GitHub Actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()